version: '3.9'

services:
  backend:
    networks:
     - backend
    container_name: kpd-bakcend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    env_file:
      - .env 

  frontend:
    networks:
      - frontend
    container_name: kpd-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4001:80

  postgres:
    networks:
      - backend
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  adminer: 
    networks:
      - backend
    container_name: adminer
    image: adminer
    ports:
      - 8081:8080

networks:
  frontend:
  backend:

volumes:
  postgres_data: