version: '3.9'

services:
  backend:
    networks:
     - backend
    container_name: kpd-bakcend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    env_file:
      - .env 
    restart: on-failure   

  frontend:
    networks:
      - frontend
    container_name: kpd-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4001:80
    restart: on-failure   

  postgres:
    networks:
      - backend
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/data/postgres
    env_file:
      - .env
    restart: on-failure   

  adminer: 
    networks:
      - backend
    container_name: adminer
    image: adminer
    ports:
      - 8081:8080
    restart: on-failure   

networks:
  frontend:
  backend:

volumes:
  postgres_data: